name: Release
on:
  release:
    types: [created]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn run build
          yarn test
      - name: Archive contract ABI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: abi-artifacts
          path: |
            build/contracts
  release:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: abi-artifacts
          path: ./build/contracts
      - name: yarn install
        run: yarn install
      - name: Authenticate with GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
      - name: Publish to GitHub Packages
      - run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}